[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace --chip with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F401RE"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"